name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: |
          pip install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint (black)
        run: |
          poetry run black --check .
      - name: Lint (isort)
        run: |
          poetry run isort --check-only .
      - name: Lint (flake8)
        run: |
          poetry run flake8 .
      - name: Type check (mypy)
        run: |
          poetry run mypy .
      - name: Run tests
        run: |
          poetry run pytest
